Repository Bugbusters-03/hotel-api, pull requests merged in 2024-07, with the labels that each got.

#1 initial commit
  .gitignore
  README.md
  erd.png
  index.js
  package-lock.json
  package.json
  src/config/text.md
  src/controllers/text.md
  src/helpers/text.md
  src/middlewares/text.md
  src/models/text.md
  src/routes/text.md
Labels: documentation

#3 Ibrsec auths
  index.js
  src/config/dbConnection.js
  src/controllers/tokenController.js
  src/middlewares/errorHandler.js
  src/models/tokenModel.js
  src/routes/tokenRouter.js
Labels: enhancement

#4 users
  index.js
  src/controllers/tokenController.js
  src/controllers/userController.js
  src/helpers/passwordEncrypt.js
  src/models/userModel.js
  src/routes/userRouter.js
Labels: bug
