Repository Bugbusters-03/hotel-api, pull requests merged in 2024-08, with the labels that each got.

#7 room added
  index.js
  src/controllers/roomController.js
  src/models/roomModel.js
  src/models/userModel.js
  src/routes/roomRouter.js
Labels: documentation

#8 User beyza
  src/controllers/roomController.js
  src/models/userModel.js
Labels: bug

#9 Ibrsec auths
  README.md
  env-sample
  index.js
  package-lock.json
  package.json
  src/controllers/authController.js
  src/controllers/userController.js
  src/middlewares/authentication.js
  src/middlewares/permission.js
  src/routes/authRouter.js
  src/routes/tokenRouter.js
  src/routes/userRouter.js
Labels: enhancement
